'use babel';

const keyMirror = require('keymirror');

export default keyMirror({
  BREAKPOINT_CREATE_REQUEST: null,
  BREAKPOINT_CREATE_SUCCESS: null,
  BREAKPOINT_CREATE_FAILURE: null,

  BREAKPOINT_SET_COND_REQUEST: null,
  BREAKPOINT_SET_COND_SUCCESS: null,
  BREAKPOINT_SET_COND_FAILURE: null,

  BREAKPOINT_CLEAR_REQUEST: null,
  BREAKPOINT_CLEAR_SUCCESS: null,
  BREAKPOINT_CLEAR_FAILURE: null,

  BREAKPOINT_CLEAR_ALL_REQUEST: null,
  BREAKPOINT_CLEAR_ALL_SUCCESS: null,
  BREAKPOINT_CLEAR_ALL_FAILURE: null
});
